from __future__ import annotations

from typing import Any, Self

import yaml
from pydantic import BaseModel, Field, model_validator

from .battery import Battery
from .constraint import Constraint
from .fault_management import FaultManagement
from .groundstation import GroundStationRegistry
from .instrument import Payload
from .observation_categories import ObservationCategories
from .recorder import OnboardRecorder
from .solar_panel import SolarPanelSet
from .spacecraft_bus import SpacecraftBus
from .targets import TargetConfig
from .visualization import VisualizationConfig


class MissionConfig(BaseModel):
    """
    Configuration class for the spacecraft and its subsystems.
    """

    name: str = Field(default="Default Config", description="Mission name/identifier")
    spacecraft_bus: SpacecraftBus = Field(
        default_factory=SpacecraftBus,
        description="Spacecraft Bus Configuration. Defines the main spacecraft platform including power, attitude control, and communications",
    )
    solar_panel: SolarPanelSet = Field(
        default_factory=SolarPanelSet,
        description="Solar Panel Configuration. Defines solar array characteristics and power generation capability",
    )
    payload: Payload = Field(
        default_factory=Payload,
        description="Payload/Instrument Configuration. Defines science instruments with power draw and data generation rates",
    )
    battery: Battery = Field(
        default_factory=Battery,
        description="Battery Configuration. Defines battery capacity, voltage, and charging parameters",
    )
    constraint: Constraint = Field(
        default_factory=Constraint,
        description="Pointing Constraints. Defines geometric constraints for spacecraft pointing",
    )
    ground_stations: GroundStationRegistry = Field(
        default_factory=GroundStationRegistry,
        description="Ground Station Network. Defines ground station locations and communication capabilities",
    )
    recorder: OnboardRecorder = Field(
        default_factory=OnboardRecorder,
        description="Onboard Data Recorder. Defines storage capacity and fill thresholds",
    )
    fault_management: FaultManagement = Field(
        default_factory=FaultManagement,
        description="Fault Management System. Defines thresholds and responses for system health monitoring",
    )
    observation_categories: ObservationCategories = Field(
        default_factory=ObservationCategories.default_categories,
        description="Observation Categories. Defines categories for different observation types with ID ranges",
    )
    visualization: VisualizationConfig = Field(
        default_factory=VisualizationConfig,
        exclude=True,
        description="Visualization Configuration",
    )
    targets: TargetConfig = Field(
        default_factory=TargetConfig,
        description="Target Configuration. Defines observational targets and scheduling parameters",
    )

    @model_validator(mode="after")
    def init_fault_management_defaults(self) -> Self:
        """Initialize default fault thresholds if none provided.

        Currently sets up a battery_level threshold using the battery
        max_depth_of_discharge as the minimum allowed charge level for YELLOW
        and (max_depth_of_discharge + 0.1) as RED for demonstration.
        Also sets up recorder_fill_fraction threshold using the recorder's
        yellow and red thresholds.
        Users can override via config serialization.
        """
        if self.fault_management is None:
            return self
        # Only add battery threshold if not already present
        if not any(t.name == "battery_level" for t in self.fault_management.thresholds):
            # Yellow alert at minimum allowed charge level (1.0 - max_depth_of_discharge)
            yellow = 1.0 - self.battery.max_depth_of_discharge
            # Red alert at 10% below the minimum allowed charge level
            red = max(yellow - 0.1, 0.0)  # Ensure non-negative
            self.fault_management.add_threshold(
                name="battery_level", yellow=yellow, red=red, direction="below"
            )
        # Add recorder threshold if not already present
        if not any(
            t.name == "recorder_fill_fraction" for t in self.fault_management.thresholds
        ):
            # Use recorder's built-in thresholds
            self.fault_management.add_threshold(
                name="recorder_fill_fraction",
                yellow=self.recorder.yellow_threshold,
                red=self.recorder.red_threshold,
                direction="above",
            )
        return self

    def data_generated(self, duration_seconds: float) -> float:
        """Calculate total data generated by spacecraft bus and payload over a duration.

        Args:
            duration_seconds: Duration of data generation in seconds.

        Returns:
            float: Total amount of data generated in Gigabits.
        """
        bus_data = self.spacecraft_bus.data_generated(duration_seconds)
        payload_data = self.payload.data_generated(duration_seconds)
        return bus_data + payload_data

    @classmethod
    def from_json_file(cls, filepath: str) -> MissionConfig:
        """Load configuration from a JSON file."""
        with open(filepath) as f:
            return cls.model_validate_json(f.read())

    def to_json_file(self, filepath: str) -> None:
        """Save configuration to a JSON file."""
        with open(filepath, "w") as f:
            f.write(self.model_dump_json(indent=4))

    @classmethod
    def from_yaml_file(cls, filepath: str) -> MissionConfig:
        """Load configuration from a YAML file.

        Args:
            filepath: Path to the YAML configuration file.

        Returns:
            MissionConfig: Validated configuration object.
        """
        with open(filepath) as f:
            config_dict = yaml.safe_load(f)
            return cls.model_validate(config_dict)

    def to_yaml_file(self, filepath: str) -> None:
        """Save configuration to a YAML file with annotations.

        The YAML output includes helpful comments explaining:
        - Default units for physical quantities (e.g., power in Watts, time in seconds)
        - Purpose and meaning of configuration settings
        - Valid ranges or constraints where applicable

        Args:
            filepath: Path where the YAML file will be written.
        """
        config_dict = self.model_dump(mode="json", exclude_none=False)

        # Build annotated YAML with comments
        yaml_lines = []
        yaml_lines.append("# COAST-Sim Mission Configuration File")
        yaml_lines.append("# Generated YAML configuration with annotations")
        yaml_lines.append("#")
        yaml_lines.append(
            "# This file defines the complete spacecraft configuration including:"
        )
        yaml_lines.append("#   - Spacecraft bus and subsystems")
        yaml_lines.append("#   - Power generation and storage")
        yaml_lines.append("#   - Payload instruments")
        yaml_lines.append("#   - Ground stations")
        yaml_lines.append("#   - Operational constraints")
        yaml_lines.append("#")
        yaml_lines.append("# Units Legend:")
        yaml_lines.append("#   Power: Watts (W)")
        yaml_lines.append("#   Energy: Watt-hours (Wh)")
        yaml_lines.append("#   Time: seconds (s) unless otherwise specified")
        yaml_lines.append("#   Angles: degrees (deg)")
        yaml_lines.append(
            "#   Data rates: Gigabits per second (Gbps) or Megabits per second (Mbps)"
        )
        yaml_lines.append("#   Data volume: Gigabits (Gb) or Gigabytes (GB)")
        yaml_lines.append("#   Slew rates: degrees per second (deg/s)")
        yaml_lines.append("#   Acceleration: degrees per second squared (deg/s²)")
        yaml_lines.append("")

        # Helper to get field description from model
        def get_field_description(field_name: str) -> str | None:
            """Get description from field metadata."""
            field_info = self.__class__.model_fields.get(field_name)
            if field_info and field_info.description:
                return field_info.description
            return None

        # Add mission name
        name_desc = get_field_description("name")
        if name_desc:
            yaml_lines.append(f"# {name_desc}")
        yaml_lines.append(f'name: "{config_dict["name"]}"')
        yaml_lines.append("")

        # Spacecraft bus section
        bus_desc = get_field_description("spacecraft_bus")
        if bus_desc:
            yaml_lines.append(f"# {bus_desc}")
        yaml_lines.append("spacecraft_bus:")
        self._add_bus_annotations(yaml_lines, config_dict["spacecraft_bus"])
        yaml_lines.append("")

        # Solar panel section
        solar_desc = get_field_description("solar_panel")
        if solar_desc:
            yaml_lines.append(f"# {solar_desc}")
        yaml_lines.append("solar_panel:")
        self._add_yaml_content(yaml_lines, config_dict["solar_panel"], indent=1)
        yaml_lines.append("")

        # Payload section
        payload_desc = get_field_description("payload")
        if payload_desc:
            yaml_lines.append(f"# {payload_desc}")
        yaml_lines.append("payload:")
        self._add_yaml_content(yaml_lines, config_dict["payload"], indent=1)
        yaml_lines.append("")

        # Battery section
        battery_desc = get_field_description("battery")
        if battery_desc:
            yaml_lines.append(f"# {battery_desc}")
        yaml_lines.append("battery:")
        self._add_yaml_content(yaml_lines, config_dict["battery"], indent=1)
        yaml_lines.append("")

        # Constraints section
        constraint_desc = get_field_description("constraint")
        if constraint_desc:
            yaml_lines.append(f"# {constraint_desc}")
        yaml_lines.append("constraint:")
        self._add_yaml_content(yaml_lines, config_dict["constraint"], indent=1)
        yaml_lines.append("")

        # Ground stations section
        ground_stations_desc = get_field_description("ground_stations")
        if ground_stations_desc:
            yaml_lines.append(f"# {ground_stations_desc}")
        yaml_lines.append("ground_stations:")
        self._add_yaml_content(yaml_lines, config_dict["ground_stations"], indent=1)
        yaml_lines.append("")

        # Recorder section
        recorder_desc = get_field_description("recorder")
        if recorder_desc:
            yaml_lines.append(f"# {recorder_desc}")
        yaml_lines.append("recorder:")
        self._add_yaml_content(yaml_lines, config_dict["recorder"], indent=1)
        yaml_lines.append("")

        # Fault management section
        fault_desc = get_field_description("fault_management")
        if fault_desc:
            yaml_lines.append(f"# {fault_desc}")
        yaml_lines.append("fault_management:")
        self._add_yaml_content(yaml_lines, config_dict["fault_management"], indent=1)
        yaml_lines.append("")

        # Observation categories section
        obs_cat_desc = get_field_description("observation_categories")
        if obs_cat_desc:
            yaml_lines.append(f"# {obs_cat_desc}")
        yaml_lines.append("observation_categories:")
        self._add_yaml_content(
            yaml_lines, config_dict["observation_categories"], indent=1
        )
        yaml_lines.append("")

        # Targets section (if present)
        if "targets" in config_dict:
            targets_desc = get_field_description("targets")
            if targets_desc:
                yaml_lines.append(f"# {targets_desc}")
            yaml_lines.append("targets:")
            self._add_yaml_content(yaml_lines, config_dict["targets"], indent=1)

        # Write to file
        with open(filepath, "w") as f:
            f.write("\n".join(yaml_lines))

    def _add_bus_annotations(
        self, lines: list[str], bus_config: dict[str, Any], indent: int = 1
    ) -> None:
        """Add spacecraft bus configuration with inline annotations."""
        ind = "  " * indent

        lines.append(f'{ind}name: "{bus_config["name"]}"')
        lines.append(f"{ind}# Power consumption of the spacecraft bus")
        lines.append(f"{ind}power_draw:")
        self._add_yaml_content(lines, bus_config["power_draw"], indent + 1)
        lines.append(f"{ind}# Attitude control system parameters")
        lines.append(f"{ind}# slew_acceleration: Angular acceleration (deg/s²)")
        lines.append(f"{ind}# max_slew_rate: Maximum angular velocity (deg/s)")
        lines.append(f"{ind}# slew_accuracy: Pointing accuracy (deg)")
        lines.append(f"{ind}# settle_time: Time to stabilize after slew (s)")
        lines.append(f"{ind}attitude_control:")
        self._add_yaml_content(lines, bus_config["attitude_control"], indent + 1)
        if bus_config.get("communications"):
            lines.append(f"{ind}communications:")
            self._add_yaml_content(lines, bus_config["communications"], indent + 1)
        else:
            lines.append(f"{ind}communications: null")
        if bus_config.get("heater"):
            lines.append(f"{ind}# Thermal heater configuration")
            lines.append(f"{ind}heater:")
            self._add_yaml_content(lines, bus_config["heater"], indent + 1)
        else:
            lines.append(f"{ind}heater: null")
        lines.append(f"{ind}# Data generation rates")
        lines.append(f"{ind}# rate_gbps: Continuous data generation rate (Gbps)")
        lines.append(f"{ind}# per_observation_gb: Data volume per observation (GB)")
        lines.append(f"{ind}data_generation:")
        self._add_yaml_content(lines, bus_config["data_generation"], indent + 1)

    def _add_yaml_content(
        self, lines: list[str], content: dict[str, Any] | list[Any] | Any, indent: int
    ) -> None:
        """Add YAML content with proper indentation."""
        yaml_str = yaml.safe_dump(content, default_flow_style=False, sort_keys=False)
        for line in yaml_str.rstrip().split("\n"):
            if line:  # Skip empty lines
                lines.append(("  " * indent) + line)
            else:
                lines.append("")
