from pydantic import Field, model_validator

from ..common.enums import BoresightAxis
from ._base import ConfigModel
from .acs import AttitudeControlSystem
from .communications import CommunicationsSystem
from .data_generator import DataGeneration
from .power import PowerDraw
from .radiator import DefaultRadiatorConfiguration, RadiatorConfiguration
from .star_tracker import DefaultStarTrackerConfiguration, StarTrackerConfiguration
from .thermal import Heater


class SpacecraftBus(ConfigModel):
    name: str = Field(default="Default Bus", description="Name of the spacecraft bus")
    boresight_axis: BoresightAxis = Field(
        default=BoresightAxis.PLUS_X,
        description=(
            "Spacecraft body axis that is the primary pointing/boresight direction. "
            "All body-frame vectors in the config (panel normals, star tracker boresights, "
            "radiator normals) are defined in this coordinate system. "
            "Default is '+X' (historical COASTSim convention). "
            "Common alternatives: '+Z' for nadir-pointing Earth-observation buses."
        ),
    )
    power_draw: PowerDraw = Field(
        default_factory=PowerDraw,
        description="Power draw specifications for bus systems",
    )
    attitude_control: AttitudeControlSystem = Field(
        default_factory=AttitudeControlSystem,
        description="Attitude control system (ACS) configuration",
    )
    communications: CommunicationsSystem | None = Field(
        default=None, description="Communications system configuration"
    )
    heater: Heater | None = Field(
        default=None, description="Heater system configuration"
    )
    data_generation: DataGeneration = Field(
        default_factory=DataGeneration,
        description="Data generation specifications for bus-level data",
    )
    star_trackers: StarTrackerConfiguration = Field(
        default_factory=DefaultStarTrackerConfiguration,
        description="Star tracker configuration",
    )
    radiators: RadiatorConfiguration = Field(
        default_factory=DefaultRadiatorConfiguration,
        description="Body-mounted radiator configuration",
    )

    @model_validator(mode="after")
    def _propagate_boresight_axis(self) -> "SpacecraftBus":
        """Propagate boresight_axis to subsystems that need it for frame conversions."""
        ba = str(self.boresight_axis)
        # Star trackers: propagate to the configuration object and each orientation
        self.star_trackers._boresight_axis = ba
        for st in self.star_trackers.star_trackers:
            st.orientation._boresight_axis = ba
        # Radiators: propagate to each radiator object
        for rad in self.radiators.radiators:
            rad._boresight_axis = ba
        return self

    def power(self, mode: int | None = None, in_eclipse: bool = False) -> float:
        """Get the power draw for the spacecraft bus in the given mode.

        Args:
            mode: Operational mode (None for nominal)
            in_eclipse: Whether spacecraft is in eclipse

        Returns:
            Total power draw in watts
        """
        base_power = self.power_draw.power(mode, in_eclipse=in_eclipse)
        heater_power = (
            self.heater.power(mode, in_eclipse=in_eclipse) if self.heater else 0.0
        )
        return base_power + heater_power

    def data_generated(self, duration_seconds: float) -> float:
        """Calculate data generated by the spacecraft bus over a given duration.

        Args:
            duration_seconds: Duration of data generation in seconds.

        Returns:
            Amount of data generated in Gigabits.
        """
        return self.data_generation.data_generated(duration_seconds)
