from pydantic import BaseModel, Field

from .acs import AttitudeControlSystem
from .communications import CommunicationsSystem
from .data_generator import DataGeneration
from .power import PowerDraw
from .star_tracker import StarTrackerConfiguration
from .thermal import Heater


class SpacecraftBus(BaseModel):
    name: str = Field(default="Default Bus", description="Name of the spacecraft bus")
    power_draw: PowerDraw = Field(
        default_factory=PowerDraw,
        description="Power draw specifications for bus systems",
    )
    attitude_control: AttitudeControlSystem = Field(
        default_factory=AttitudeControlSystem,
        description="Attitude control system (ACS) configuration",
    )
    communications: CommunicationsSystem | None = Field(
        default=None, description="Communications system configuration"
    )
    heater: Heater | None = Field(
        default=None, description="Heater system configuration"
    )
    data_generation: DataGeneration = Field(
        default_factory=DataGeneration,
        description="Data generation specifications for bus-level data",
    )
    star_trackers: StarTrackerConfiguration = Field(
        default_factory=StarTrackerConfiguration,
        description="Star tracker configuration",
    )

    def power(self, mode: int | None = None, in_eclipse: bool = False) -> float:
        """Get the power draw for the spacecraft bus in the given mode.

        Args:
            mode: Operational mode (None for nominal)
            in_eclipse: Whether spacecraft is in eclipse

        Returns:
            Total power draw in watts
        """
        base_power = self.power_draw.power(mode, in_eclipse=in_eclipse)
        heater_power = (
            self.heater.power(mode, in_eclipse=in_eclipse) if self.heater else 0.0
        )
        return base_power + heater_power

    def data_generated(self, duration_seconds: float) -> float:
        """Calculate data generated by the spacecraft bus over a given duration.

        Args:
            duration_seconds: Duration of data generation in seconds.

        Returns:
            Amount of data generated in Gigabits.
        """
        return self.data_generation.data_generated(duration_seconds)
